# PyTorch
In this exercise, we will look at some basic functionality of PyTorch. Your are free to use other DL frameworks for your exercises and your project. However, the master solutions and code examples will be in PyTorch.

The [PyTorch documentation](https://pytorch.org/docs/stable/index.html) offers information on its functionality. A lot of the time, your specific question will also have been asked on the [PyTorch Forum](https://discuss.pytorch.org/), often with competent answers by the core developers (Google will find the relevant thread for you).

First, we have to install PyTorch. We will install the basic version for this exercise. For your project, if you want to run on a GPU, you'll have to make sure to have a PyTorch version installed that is compatible with the CUDA version of your NVIDIA drivers. PyTorch has an [installation guide](https://pytorch.org/get-started/locally/) that will help you with getting the right version.

In [20]:
%pip install -q numpy
%pip install -q torch ipywidgets

Note: you may need to restart the kernel to use updated packages.
Note: you may need to restart the kernel to use updated packages.


In [21]:
import torch
import numpy as np

## Tensor operations
Most of PyTorch's operations have the same name as in NumPy. The basic object for storing data is the `torch.tensor`, the equivalent of the `np.array`. With the help of the [Tensor tutorial](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html), do the following:

- Create a `torch.tensor` with the elements `[[1, 2], [3, 4]]`
- Create an `np.array` with the same elements
- Convert from one to the other
- Check how the values of one change when you change the other
- Create a tensor of ones/zeros with the same shape and dtype
- Create a random tensor of the same shape
- Print the tensor's shape, data type and device
- Try to move it to the GPU
- Check out indexing/slicing operations, and how you can assign values to a slice.
- Combine tensors with `torch.cat` and `torch.stack`. What are the differences?
- Multiply tensors, element-wise and with matrix multiplication.

In [25]:
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
np_array = np.array(data)
x_data.numpy() # convert to numpy array from tensor
x_np = torch.from_numpy(np_array) # convert to tensor from numpy array
print(x_np)
np.add(np_array, 1, out=np_array)
print(x_np)
x_ones = torch.ones_like(x_data)
print(x_ones)
print(x_data.dtype)
torch.rand_like(x_data, dtype=torch.float32)
torch.rand(3, 4)
x_data.shape, x_data.dtype, x_data.device

if torch.cuda.is_available():
    device = 'cuda'

tensor = torch.eye(4, 4)
print(tensor[:2, 1:3])

print(x_data)

# element-wise multiply
print(x_data + 1)

# matrix multiply
x_data * (x_data + 1)
x_data.matmul(x_data + 1)
torch.matmul(x_data, x_data + 1)



tensor([[1, 2],
        [3, 4]])
tensor([[2, 3],
        [4, 5]])
tensor([[1, 1],
        [1, 1]])
torch.int64
tensor([[0., 0.],
        [1., 0.]])
tensor([[1, 2],
        [3, 4]])
tensor([[2, 3],
        [4, 5]])


tensor([[10, 13],
        [22, 29]])

## Neural Network Basics
Solve the followings tasks with the help of the [Neural networks tutorial](https://pytorch.org/tutorials/beginner/blitz/neural_networks_tutorial.html).

The `nn.Module` is the basic class for layers, networks and models. All parameters of an `nn.Module` are automatically discovered by PyTorch and updated by back-propagation.

First, define a neural network (as a subclass of `nn.Module`) with two linear layers and a ReLU non-linearity in between. Make the input, output, and inner dimensions parameters of your network.

In [26]:
import torch.nn as nn

In [40]:
class MyNetwork(nn.Module):

    def __init__(self, input_dim, output_dim, inner_dim):
        super(MyNetwork, self).__init__()
        # 2 linear layers with ReLU
        self._model = nn.Sequential(
            nn.Linear(input_dim, inner_dim),
            nn.ReLU(),
            nn.Linear(inner_dim, output_dim)
        )
    
    def forward(self, x):
        return self._model(x)

my_net = MyNetwork(10, 2, 5).to(device)
        

Print the parameters of your network.

In [41]:
params = list(my_net.parameters())

for name, param in my_net.named_parameters():
    print(name, param.shape)

params

_model.0.weight torch.Size([5, 10])
_model.0.bias torch.Size([5])
_model.2.weight torch.Size([2, 5])
_model.2.bias torch.Size([2])


[Parameter containing:
 tensor([[ 0.3041, -0.1274,  0.2942,  0.2161,  0.2629, -0.2483, -0.0860, -0.2185,
           0.0674,  0.0713],
         [-0.2970, -0.2218,  0.0132, -0.2014, -0.0238, -0.1338,  0.2794,  0.1872,
          -0.1216, -0.0619],
         [ 0.0428,  0.0579, -0.1894, -0.2215,  0.2458, -0.1753, -0.2024, -0.0506,
           0.0124,  0.1499],
         [-0.2182,  0.2671, -0.2178, -0.2616,  0.1253,  0.1028, -0.3122,  0.0724,
          -0.1263,  0.1842],
         [-0.2644,  0.0302,  0.2926,  0.2210,  0.2716, -0.1307, -0.1425,  0.0403,
          -0.0054, -0.0876]], device='cuda:0', requires_grad=True),
 Parameter containing:
 tensor([ 0.1777, -0.0502, -0.0702,  0.0805,  0.2809], device='cuda:0',
        requires_grad=True),
 Parameter containing:
 tensor([[ 0.0451, -0.3512, -0.0914,  0.2857, -0.4289],
         [-0.2651, -0.1095, -0.4458,  0.0309,  0.3867]], device='cuda:0',
        requires_grad=True),
 Parameter containing:
 tensor([-0.2056,  0.0957], device='cuda:0', requires_

Run a single forward-pass with a random input.

In [42]:
x = torch.rand(4, 10).to(device)
out = my_net(x)
print(out.shape)
print(out)

torch.Size([4, 2])
tensor([[-0.4049,  0.1651],
        [-0.3828,  0.1206],
        [-0.4466,  0.2066],
        [-0.4405,  0.1808]], device='cuda:0', grad_fn=<AddmmBackward0>)


Define a `nn.MSELoss` and a random target.

In [43]:
criterion = nn.MSELoss()
y = torch.rand(4,2).to(device)

Compute the loss and run backpropagation.

In [44]:
loss = criterion(out, y)
print(loss)

my_net.zero_grad()
loss.backward()

tensor(0.4108, device='cuda:0', grad_fn=<MseLossBackward0>)


Update the parameters of your network with a learning rate of 0.01.

In [45]:
learning_rate = 0.01
for param in my_net.parameters():
    param.data = param.data - learning_rate * param.grad.data

Use the `AdamOptimizer` instead to update your parameters (see the [torch.optim documentation](https://pytorch.org/docs/stable/optim.html)).

In [46]:
optimizer = torch.optim.Adam(my_net.parameters(), lr=learning_rate)

out = my_net(x)
loss = criterion(out, y)
optimizer.zero_grad()
loss.backward()
optimizer.step()